version: "3.8"

services:
  myeiam:
    build:
      context: .
      dockerfile: Dockerfile
    image: mye-iam-service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
    command: bun run start
    restart: unless-stopped

volumes:
  node_modules:
